### ISSUE TITLE
ensure hides actual errors in failing tests

### ISSUE THREAD

**Issue by dheles** [kbsecret/kbsecret#52]
Please make sure to fill out everything below to help us with your issue!

* Ruby version (`ruby -v`): ruby 2.4.2p198
* KBSecret version (`kbsecret -v`):  kbsecret version 0.9.5.

## Problem

ending test methods with `ensure` hides the error message that would describe the actual problem when a cli test fails 

## Replication

write a cli test wherein a record create step fails for whatever reason

## Expected behavior

the test reports the error regarding the failed create step
e.g. "`kbsecret new login` failed because too few arguments"

## Actual behavior

the test reports the error regarding the cleanup step in the `ensure` block
e.g. "`kbsecret rm login` failed because no such record"

## Proposed solution

don't use `ensure` in the tests 

Thank you!

**Comment by woodruffw** [comment]
Can you provide a minimal example? I'm not following.

`ensure` should *never* mask an error message, since `kbsecret` error messages get propagated on `stderr` right before an exit. `ensure` blocks are only executed at method return *or* when an exception is raised.

**Comment by dheles** [comment]
sure. it you take a test like `test_pass` in `test_pass.rb` and change the conditions so that something upstream of the `ensure` block will fail, say setting the value of `label` to an empty string, rather than a valid value, with `ensure`, you get an error about the failed cleanup: 

```Error:
CLIPassTest#test_pass:
RSpec::Expectations::ExpectationNotMetError: expected "kbsecret rm " to be successfully executed
```

... a symptom of the problem, but not the cause.

without `ensure`, you get:

```
  1) Failure:
CLIPassTest#test_pass [test/cli/test_pass.rb:30]:
--- expected
+++ actual
@@ -1 +1 @@
-"pass"
+"\e[31mFatal\e[0m: Too few arguments given (0, expected 1)."
```
...which accurately reports the problem you'd need to fix to get the test to pass

**Comment by woodruffw** [comment]
Oh, I see. Hmm.

The problem is that we *need* to perform the cleanup - people will be running these tests on their local machines, and I don't want to leave their KBSecret installations in an inconsistent/unknown state. Furthermore, the unit tests should be functionally stateless - subsequent runs of `make test` and `make test-cli` should not fail because of a previous run.

I *think* something like this will work:

```ruby
def test_whatever
  # assertions here
rescue => e
  puts e
ensure
  # cleanup here
end
```

I can't find it now, but this could be abstracted away into the `kbsecret` helper method I suggested before.

**Comment by woodruffw** [comment]
Found it: https://github.com/kbsecret/kbsecret/pull/35#issuecomment-337739463

That could be modified to use Aruba instead of Open3 and do the exception catching above.

**Comment by dheles** [comment]
i like the `rescue` idea, as it seems like it will integrate well into our existing tests. i'm not entirely following your helper example yet. however, what i'd really like to do at the moment is continue with the `ensure` blocks, even with this known issue, until we have the test suite finished. then we can loop back, solve the issue in a good way that provides informative error messages *and* leaves a clean environment in their wake, and apply it to all the tests.

**Comment by dheles** [comment]
HA! you've already provided an easy solution: just add `--no-warn` to the cleanup methods in the `ensure` block. if they fail, they'll do so quietly, so we can see the actual error from the earlier failure

**Comment by woodruffw** [comment]
> HA! you've already provided an easy solution: just add --no-warn to the cleanup methods in the ensure block. if they fail, they'll do so quietly, so we can see the actual error from the earlier failure

Does that actually work? `--no-warn` should only be suppressing warnings, not actual errors.

**Comment by dheles** [comment]
well, a failure to remove a non-existent record could fairly be interpreted as a warning, rather than an error, i think. and yes, it does work to address the problem.

**Comment by woodruffw** [comment]
> well, a failure to remove a non-existent record could fairly be interpreted as a warning, rather than an error, i think.

Emphasis on failure - if it prevents the command from functioning as expected, I've implemented it as an error (i.e., `cmd.die`). If it can be worked around, I've implemented it as a warning (i.e., `cmd.warn`). See `kbsecret session`'s source for good examples of both.

That's why I'm confused that `--no-warn` is working - `cmd.die` doesn't check its state at all, so it should have no effect on error output (like when `kbsecret rm` fails). The fact that it *is* working might be a bug.

**Comment by dheles** [comment]
i'm actually working on other tests in the suite at the moment. once i'm done, i'll submit something that demonstrates what works and what doesn't, so things are clearer. so far, though, `--no-warn` isn't as complete a solution as i was thinking it was
